require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - '.git/**/*'
    - "**/templates/**/*"
    - "bin/*"
    - "db/migrate/*"
  NewCops: enable

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - "**/*.rake"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/DynamicFindBy:
  Exclude:
    - "spec/models/*.rb"
