require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - lib/**/*.rake
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - "**/templates/**/*"
    - "*.gemspec"
    - "bin/*"
  NewCops: enable

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - "**/*.rake"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/DynamicFindBy:
  Exclude:
    - "spec/models/*.rb"
