require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - '.git/**/*'
    - "**/templates/**/*"
    - "bin/*"
    - "db/migrate/*"
  NewCops: enable

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - "**/*.rake"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
